AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
   SAM Template for {{cookiecutter.project_name}}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
  
Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment (dev, qa, val, prod)

Resources:
  ServerLessExecFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: {{cookiecutter.function_iam_role}}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: {{cookiecutter.api_logical_name}}
      StageName: !Ref Environment
  ServerLessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Role: !GetAtt ServerLessExecFunctionRole.Arn
      {%- if cookiecutter.architectures.value != []%}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{arch}}
      {%- endfor %}
      {%- endif %}
      FunctionName: {{cookiecutter.function_logical_name}} 
      Events:
        EventApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ServiceApi
            Path: /{{cookiecutter.event_res_path}}
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: {{cookiecutter.runtime}}

Outputs:
  # ServiceApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ServiceApi:
    Description: "API Gateway endpoint URL for Stage environment for ServerLess function"
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/{{cookiecutter.event_res_path}}/"
  ServerLessFunction:
    Description: "Serverless Lambda Function ARN"
    Value: !GetAtt ServerLessFunction.Arn
  ServerLessExecFunctionRole:
    Description: "Implicit IAM Role created for ServerLess function"
    Value: !GetAtt ServerLessExecFunctionRole.Arn